<?php
require_once 'fpdf186/fpdf.php';

class CertificatePDF extends FPDF
{
    function Header()
    {
        $this->SetFont('Helvetica', 'B', 18);
        $this->SetTextColor(30, 41, 59);
        $this->Cell(0, 12, 'CyberQuest Certificate', 0, 1, 'C');
        $this->Ln(5);
    }

    function Footer()
    {
        $this->SetY(-18);
        $this->SetFont('Helvetica', 'I', 9);
        $this->SetTextColor(120, 120, 120);
        $this->Cell(0, 10, 'Generated by CyberQuest', 0, 0, 'C');
    }
}

$name  = isset($_GET['name']) ? trim($_GET['name']) : 'Student';
$level = isset($_GET['level']) ? (int)$_GET['level'] : 1;
$score = isset($_GET['score']) ? (int)$_GET['score'] : 0;
$total = isset($_GET['total']) ? (int)$_GET['total'] : 100;

$pdf = new CertificatePDF('L', 'mm', 'A4');
$pdf->AddPage();

$pdf->SetFillColor(12, 18, 38);
$pdf->Rect(0, 0, 297, 210, 'F');

$pdf->SetDrawColor(88, 204, 2);
$pdf->SetLineWidth(2);
$pdf->Rect(10, 10, 277, 190);

$pdf->SetFont('Helvetica', 'B', 28);
$pdf->SetTextColor(255, 255, 255);
$pdf->SetY(35);
$pdf->Cell(0, 15, 'CERTIFICATE OF ACHIEVEMENT', 0, 1, 'C');

$pdf->SetFont('Helvetica', '', 16);
$pdf->Cell(0, 10, 'This certificate is proudly presented to', 0, 1, 'C');

$pdf->Ln(8);
$pdf->SetFont('Helvetica', 'B', 30);
$pdf->SetTextColor(255, 217, 0);
$pdf->Cell(0, 14, strtoupper($name), 0, 1, 'C');

$pdf->Ln(6);
$pdf->SetFont('Helvetica', '', 15);
$pdf->SetTextColor(240, 240, 240);
$pdf->Cell(0, 10, 'for successfully completing the CyberQuest quiz', 0, 1, 'C');
$pdf->Cell(0, 10, 'and reaching Level ' . $level, 0, 1, 'C');

$pdf->Ln(8);
$pdf->SetFont('Helvetica', 'B', 18);
$pdf->SetTextColor(88, 204, 2);
$pdf->Cell(0, 10, 'Score: ' . $score . ' / ' . $total, 0, 1, 'C');

$pdf->Ln(14);
$pdf->SetFont('Helvetica', '', 12);
$pdf->SetTextColor(180, 180, 180);
$pdf->Cell(0, 8, 'Date: ' . date('d M Y'), 0, 1, 'C');

$pdf->Ln(12);
$pdf->SetFont('Helvetica', 'B', 14);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(0, 8, 'CyberQuest Team', 0, 1, 'C');

$pdf->Output('I', 'CyberQuest_Certificate.pdf');
?>